services:
  db:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - type: volume
        source: mydb
        target: /data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  server:
    build: .
    container_name: app_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./src
        target: /app/src
    environment:
      - MONGO_PWD
      - MONGO_USERNAME
    depends_on:
      - db
volumes:
  mydb:
    external: true
